#!/usr/bin/env bash
# Install and configure HAproxy on load balancer.

apt-get -y update
apt-get -y install haproxy
sed -i -e "\$aENABLED=1" /etc/default/haproxy
sed -i -e "\$afrontend http\n\tbind *:80\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 310574-web-01 52.87.255.240:80 check\n\tserver 310574-web-02 52.86.177.0:80 check" /etc/haproxy/haproxy.cfg
service haproxy restart
