#!/usr/bin/env bash
# Bash script that displays listening ports to:
# That only shows listening sockets
# That shows the PID and name of the program to which each socket belongs to

sudo netstat -tulp
