#!/usr/bin/env bash

# Update packages
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Start Nginx service
sudo systemctl start nginx

# Enable Nginx service so it starts on boot
sudo systemctl enable nginx

# Check if Nginx is running
if systemctl status nginx | grep -q 'running'; then
    echo "Nginx is running"
else
    echo "Nginx is not running"
    exit 1
fi

# Check if Nginx is listening on port 80
if netstat -plntu | grep -q ':80 '; then
    echo "Nginx is listening on port 80"
else
    echo "Nginx is not listening on port 80"
    exit 1
fi
