#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but in 9 iteration it say hi
x=1
while [ $x -le 10 ]
do
	echo "Best School"
	if [ $x -eq 9 ]
	then
		echo "Hi"
	fi
	((x++))
done
