#!/usr/bin/env bash
# Configure nginx as user and listen on all active IPs on port 8080.

if ! command -v nginx &> /dev/null;
then
	apt-get update
	apt-get install -y nginx
fi

service nginx stop

sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.config
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default

service nginx restart
